
name: Worthify
version: 1.0.1
main: dev.simpleye.worthify.WorthifyPlugin
author: "YE"
discord: "._.ye"
github: "https://github.com/s1mple-ye/Worthify"
modrinth: "https://modrinth.com/plugin/worthify"
api-version: '1.21'
folia-supported: true
is-folia: true
softdepend:
  - Vault
  - PlaceholderAPI
  - ProtocolLib
commands:
  sell:
    description: Sell items for money
    usage: /sell [hand|all]
    permission: worthify.sell
  multiplier:
    description: View and edit worth multipliers (when enabled)
    usage: /multiplier
    aliases: [mult]
    permission: worthify.sell
  balance:
    description: View your balance
    usage: /balance
    aliases: [bal]
    permission: worthify.sell
  baltop:
    description: View the richest players (internal economy)
    usage: /baltop [limit]
    aliases: [topbal, topbalance, balancetop, top]
    permission: worthify.sell
  deleteworth:
    description: Reset a player's internal balance
    usage: /deleteworth <player>
    permission: worth.delete
  pay:
    description: Pay another player money
    usage: /pay <player> <amount>
    permission: worthify.sell
  paytoggle:
    description: Toggle whether you can receive payments
    usage: /paytoggle
    permission: worthify.sell
  setworth:
    description: Set worth value for the item in your main hand
    usage: /setworth <number>
    permission: worthify.admin
  worth:
    description: View all item worth values
    usage: /worth [page]
    permission: worthify.sell
  sellhistory:
    description: View your sell history
    usage: /sellhistory [page]
    permission: worthify.sell
  worthify:
    description: Worthify admin command
    usage: /worthify <help|version|reload>
    permission: worthify.admin
  takemoney:
    description: Take money from a player
    usage: /takemoney <player> <amount>
    permission: worthify.takemoney
  givemoney:
    description: Give money to a player
    usage: /givemoney <player> <amount>
    permission: worthify.givemoney
permissions:
  worthify.*:
    default: op
    children:
      worthify.sell: true
      worthify.admin: true
      worthify.takemoney: true
      worthify.givemoney: true
      worthify.update: true
      worth.delete: true
  worthify.sell:
    default: true
  worthify.admin:
    default: op
  worthify.takemoney:
    default: op
  worthify.givemoney:
    default: op
  worthify.update:
    default: op
  worth.delete:
    default: op
